# Generated by Django 4.2.7 on 2024-01-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opponents',
            new_name='Opponent',
        ),
    ]
