# Generated by Django 4.2.7 on 2024-03-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatchstatistics',
            name='match',
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
